# Generated by Django 4.1.5 on 2023-01-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50, verbose_name="Nom de l'étudiant")),
                ('prenom', models.CharField(max_length=50, verbose_name="Prénom de l'étudiant")),
                ('salle_de_classe', models.CharField(max_length=10)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=50)),
                ('numero_de_telephone', models.PositiveIntegerField()),
            ],
        ),
    ]
