# Generated by Django 4.1.5 on 2023-01-14 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Etudiant',
        ),
    ]
