# Generated by Django 4.1.5 on 2023-01-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_etudiant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Critere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('note_maximale', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Critere',
                'verbose_name_plural': 'Criteres',
            },
        ),
    ]
