# Generated by Django 4.1.5 on 2023-01-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_notation'),
    ]

    operations = [
        migrations.AddField(
            model_name='notation',
            name='remarque',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
